# Generated by Django 4.2.6 on 2023-10-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUBSCRIBER', 'Abonné'), ('CREATOR', 'Créateur')], max_length=30),
        ),
    ]
